<?php
/**
 * Frontend JSON-LD generation.
 */

defined( 'ABSPATH' ) || exit;

/**
 * Remove empty values recursively.
 *
 * Keeps numeric zero and boolean false, but removes:
 * - null
 * - empty strings
 * - empty arrays
 *
 * @param mixed $value Value to clean.
 * @return mixed
 */
function sos_schema_clean_value( $value ) {
	if ( is_array( $value ) ) {
		$value = array_map( 'sos_schema_clean_value', $value );

		$value = array_filter(
			$value,
			static function ( $item ) {
				return null !== $item && '' !== $item && array() !== $item;
			}
		);
	}

	return $value;
}

/**
 * Convert an ACF image value to a public URL.
 *
 * Supports ACF image return formats:
 * - Image array
 * - Attachment ID
 * - URL
 *
 * @param mixed $image ACF image value.
 * @return string
 */
function sos_schema_image_url( $image ) {
	if ( is_array( $image ) && ! empty( $image['url'] ) ) {
		return esc_url_raw( $image['url'] );
	}

	if ( is_numeric( $image ) ) {
		$url = wp_get_attachment_image_url( (int) $image, 'full' );
		return $url ? esc_url_raw( $url ) : '';
	}

	if ( is_string( $image ) ) {
		return esc_url_raw( $image );
	}

	return '';
}

/**
 * Decode the "Additional JSON-LD Properties" textarea.
 *
 * The value must be a JSON object. Reserved properties cannot replace
 * values generated by the structured fields.
 *
 * @param string $json          Raw JSON entered in ACF.
 * @param array  $reserved_keys Keys that cannot be overridden.
 * @return array
 */
function sos_schema_decode_additional_properties( $json, $reserved_keys = array() ) {
	if ( ! is_string( $json ) || '' === trim( $json ) ) {
		return array();
	}

	$decoded = json_decode( wp_unslash( $json ), true );

	if ( JSON_ERROR_NONE !== json_last_error() || ! is_array( $decoded ) ) {
		return array();
	}

	foreach ( $reserved_keys as $reserved_key ) {
		unset( $decoded[ $reserved_key ] );
	}

	return $decoded;
}

/**
 * Build a Schema.org PostalAddress.
 *
 * @param mixed $address ACF group field value.
 * @return array
 */
function sos_schema_build_address( $address ) {
	if ( ! is_array( $address ) ) {
		return array();
	}

	return sos_schema_clean_value(
		array(
			'@type'           => 'PostalAddress',
			'streetAddress'    => sanitize_text_field( $address['schema_street_address'] ?? '' ),
			'addressLocality'  => sanitize_text_field( $address['schema_address_locality'] ?? '' ),
			'addressRegion'    => sanitize_text_field( $address['schema_address_region'] ?? '' ),
			'postalCode'       => sanitize_text_field( $address['schema_postal_code'] ?? '' ),
			'addressCountry'   => strtoupper( sanitize_text_field( $address['schema_address_country'] ?? '' ) ),
		)
	);
}

/**
 * Normalize an array of URLs from an ACF repeater.
 *
 * @param mixed $rows ACF repeater value.
 * @return array
 */
function sos_schema_profile_urls( $rows ) {
	if ( ! is_array( $rows ) ) {
		return array();
	}

	$urls = array();

	foreach ( $rows as $row ) {
		$url = esc_url_raw( $row['schema_url'] ?? '' );

		if ( $url ) {
			$urls[] = $url;
		}
	}

	return array_values( array_unique( $urls ) );
}

/**
 * Build openingHoursSpecification values.
 *
 * @param mixed $rows ACF opening-hours repeater value.
 * @return array
 */
function sos_schema_opening_hours( $rows ) {
	if ( ! is_array( $rows ) ) {
		return array();
	}

	$hours = array();

	foreach ( $rows as $row ) {
		$days = $row['schema_day_of_week'] ?? array();

		if ( is_string( $days ) && '' !== $days ) {
			$days = array( $days );
		}

		if ( ! is_array( $days ) || empty( $days ) ) {
			continue;
		}

		$days = array_values(
			array_filter(
				array_map( 'sanitize_text_field', $days )
			)
		);

		$opens  = sanitize_text_field( $row['schema_opens'] ?? '' );
		$closes = sanitize_text_field( $row['schema_closes'] ?? '' );

		if ( empty( $days ) || ! $opens || ! $closes ) {
			continue;
		}

		$hours[] = array(
			'@type'     => 'OpeningHoursSpecification',
			'dayOfWeek' => $days,
			'opens'     => $opens,
			'closes'    => $closes,
		);
	}

	return $hours;
}

/**
 * Build areaServed values from the LocalBusiness repeater.
 *
 * @param mixed $rows ACF areas-served repeater value.
 * @return array
 */
function sos_schema_areas_served( $rows ) {
	if ( ! is_array( $rows ) ) {
		return array();
	}

	$areas = array();

	foreach ( $rows as $row ) {
		$area = sanitize_text_field( $row['schema_area'] ?? '' );

		if ( $area ) {
			$areas[] = $area;
		}
	}

	return array_values( array_unique( $areas ) );
}

/**
 * Build the main Organization entity.
 *
 * @param array $fields Options-page fields.
 * @return array
 */
function sos_schema_build_organization( $fields ) {
	if ( empty( $fields['schema_enable_schema'] ) ) {
		return array();
	}

	$schema_id = esc_url_raw( $fields['schema_id'] ?? '' );
	$name      = sanitize_text_field( $fields['schema_name'] ?? '' );
	$url       = esc_url_raw( $fields['schema_url'] ?? '' );

	// Avoid outputting an incomplete primary entity.
	if ( ! $schema_id || ! $name || ! $url ) {
		return array();
	}

	$organization = array(
		'@type'         => 'Organization',
		'@id'           => $schema_id,
		'name'          => $name,
		'legalName'     => sanitize_text_field( $fields['schema_legal_name'] ?? '' ),
		'alternateName' => sanitize_text_field( $fields['schema_alternate_name'] ?? '' ),
		'url'           => $url,
		'description'   => sanitize_textarea_field( $fields['schema_description'] ?? '' ),
		'logo'          => sos_schema_image_url( $fields['schema_logo'] ?? '' ),
		'foundingDate'  => sanitize_text_field( $fields['schema_founding_date'] ?? '' ),
		'telephone'     => sanitize_text_field( $fields['schema_telephone'] ?? '' ),
		'email'         => sanitize_email( $fields['schema_email'] ?? '' ),
		'address'       => sos_schema_build_address( $fields['schema_address'] ?? array() ),
		'sameAs'        => sos_schema_profile_urls( $fields['schema_same_as'] ?? array() ),
	);

	$additional = sos_schema_decode_additional_properties(
		$fields['schema_additional_json_ld'] ?? '',
		array( '@context', '@type', '@id' )
	);

	// Structured ACF fields take priority over additional properties.
	$organization = array_merge( $additional, $organization );

	return sos_schema_clean_value( $organization );
}

/**
 * Build all enabled LocalBusiness entities.
 *
 * @param array  $fields          Options-page fields.
 * @param string $organization_id Main Organization @id.
 * @param bool   $link_to_org     Whether the Organization is being emitted.
 * @return array
 */
function sos_schema_build_local_businesses( $fields, $organization_id, $link_to_org ) {
	if (
		empty( $fields['schema_enable_local_business_schema'] ) ||
		empty( $fields['schema_local_business_locations'] ) ||
		! is_array( $fields['schema_local_business_locations'] )
	) {
		return array();
	}

	$entities      = array();
	$allowed_types = array(
		'LocalBusiness',
		'ProfessionalService',
		'Store',
		'Restaurant',
		'MedicalBusiness',
		'FinancialService',
		'HomeAndConstructionBusiness',
		'RealEstateAgent',
	);

	foreach ( $fields['schema_local_business_locations'] as $location ) {
		if ( empty( $location['schema_enable_location'] ) ) {
			continue;
		}

		$type = sanitize_text_field( $location['schema_business_type'] ?? 'LocalBusiness' );

		if ( ! in_array( $type, $allowed_types, true ) ) {
			$type = 'LocalBusiness';
		}

		$schema_id = esc_url_raw( $location['schema_id'] ?? '' );
		$name      = sanitize_text_field( $location['schema_name'] ?? '' );
		$address   = sos_schema_build_address( $location['schema_address'] ?? array() );

		// A location needs a unique ID, name, and usable address.
		if ( ! $schema_id || ! $name || empty( $address['streetAddress'] ) || empty( $address['addressLocality'] ) || empty( $address['addressCountry'] ) ) {
			continue;
		}

		$latitude  = $location['schema_latitude'] ?? '';
		$longitude = $location['schema_longitude'] ?? '';
		$geo       = array();

		if ( is_numeric( $latitude ) && is_numeric( $longitude ) ) {
			$geo = array(
				'@type'     => 'GeoCoordinates',
				'latitude'  => (float) $latitude,
				'longitude' => (float) $longitude,
			);
		}

		$entity = array(
			'@type'        => $type,
			'@id'          => $schema_id,
			'name'         => $name,
			'url'          => esc_url_raw( $location['schema_url'] ?? '' ),
			'image'        => sos_schema_image_url( $location['schema_image'] ?? '' ),
			'telephone'    => sanitize_text_field( $location['schema_telephone'] ?? '' ),
			'email'        => sanitize_email( $location['schema_email'] ?? '' ),
			'address'      => $address,
			'geo'          => $geo,
			'hasMap'       => esc_url_raw( $location['schema_has_map'] ?? '' ),
			'openingHoursSpecification' => sos_schema_opening_hours(
				$location['schema_opening_hours'] ?? array()
			),
			'priceRange'   => sanitize_text_field( $location['schema_price_range'] ?? '' ),
			'areaServed'   => sos_schema_areas_served(
				$location['schema_areas_served'] ?? array()
			),
		);

		if ( $link_to_org && $organization_id ) {
			$entity['branchOf'] = array(
				'@id' => $organization_id,
			);
		}

		$additional = sos_schema_decode_additional_properties(
			$location['schema_additional_json_ld'] ?? '',
			array( '@context', '@type', '@id', 'branchOf' )
		);

		// Structured ACF fields take priority over additional properties.
		$entity = array_merge( $additional, $entity );
		$entity = sos_schema_clean_value( $entity );

		if ( $entity ) {
			$entities[] = $entity;
		}
	}

	return $entities;
}

/**
 * Output the JSON-LD graph in the document head.
 *
 * @return void
 */
function sos_output_organization_schema() {
	if ( ! function_exists( 'get_fields' ) ) {
		return;
	}

	// ACF options-page values are global and retrieved with the "option" post ID.
	$fields = get_fields( 'option' );

	if ( ! is_array( $fields ) ) {
		return;
	}

	$organization    = sos_schema_build_organization( $fields );
	$organization_id = esc_url_raw( $fields['schema_id'] ?? '' );
	$locations       = sos_schema_build_local_businesses(
		$fields,
		$organization_id,
		! empty( $organization )
	);

	$graph = array();

	if ( $organization ) {
		$graph[] = $organization;
	}

	foreach ( $locations as $location ) {
		$graph[] = $location;
	}

	if ( empty( $graph ) ) {
		return;
	}

	$json_ld = array(
		'@context' => 'https://schema.org',
		'@graph'   => $graph,
	);

	echo "\n<script type=\"application/ld+json\">\n";
	echo wp_json_encode(
		$json_ld,
		JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT
	);
	echo "\n</script>\n";
}
