<?php
/**
 * Frontend JSON-LD generation.
 */

namespace Selectrum\OrganizationSchema;

defined( 'ABSPATH' ) || exit;

/**
 * Remove empty values recursively.
 *
 * Keeps numeric zero and boolean false, but removes:
 * - null
 * - empty strings
 * - empty arrays
 *
 * @param mixed $value Value to clean.
 * @return mixed
 */
function clean_value( $value ) {
	if ( is_array( $value ) ) {
		foreach ( $value as $key => $item ) {
			$value[ $key ] = clean_value( $item );
		}

		$value = array_filter(
			$value,
			static function ( $item ) {
				return null !== $item && '' !== $item && array() !== $item;
			}
		);
	}

	return $value;
}

/**
 * Build a schema @id from a base URL and a fragment.
 *
 * The fragments follow Yoast's conventions ("#organization", "#website",
 * "#webpage", "#breadcrumb", "#primaryimage"). Sharing those identifiers means
 * that when Yoast is active, its own references resolve to these entities
 * instead of dangling.
 *
 * @param string $fragment Fragment name, without the leading hash.
 * @param string $url      Base URL. Defaults to the site home.
 * @return string
 */
function entity_id( $fragment, $url = '' ) {
	if ( '' === $url ) {
		$url = home_url( '/' );
	}

	return esc_url_raw( $url ) . '#' . $fragment;
}

/**
 * Resolve the Organization @id.
 *
 * Always generated, never configurable. The value has to match Yoast's
 * Schema_IDs::ORGANIZATION_HASH exactly, because that identity is what keeps
 * Yoast's publisher and author references resolving to this Organization once
 * Yoast's own Organization piece is removed. A hand-typed value would break
 * that silently.
 *
 * @return string
 */
function organization_id() {
	return entity_id( 'organization' );
}

/**
 * Resolve the canonical URL of the current request.
 *
 * @return string
 */
function current_url() {
	$url = '';

	// Checked before is_home() so a blog-as-front-page resolves to the home URL.
	if ( is_front_page() ) {
		$url = home_url( '/' );
	} elseif ( is_singular() ) {
		$url = get_permalink( get_queried_object_id() );
	} elseif ( is_home() ) {
		$posts_page_id = (int) get_option( 'page_for_posts' );
		$url           = $posts_page_id ? get_permalink( $posts_page_id ) : home_url( '/' );
	} elseif ( is_category() || is_tag() || is_tax() ) {
		$term = get_queried_object();
		$url  = $term instanceof \WP_Term ? get_term_link( $term ) : '';
	} elseif ( is_post_type_archive() ) {
		$post_type = get_query_var( 'post_type' );

		// The query var is an array on archives that span several post types.
		if ( is_array( $post_type ) ) {
			$post_type = reset( $post_type );
		}

		$url = $post_type ? get_post_type_archive_link( $post_type ) : '';
	} elseif ( is_author() ) {
		$url = get_author_posts_url( get_queried_object_id() );
	} else {
		global $wp;

		$url = isset( $wp->request ) && '' !== $wp->request
			? home_url( user_trailingslashit( $wp->request ) )
			: home_url( '/' );
	}

	return is_string( $url ) ? esc_url_raw( $url ) : '';
}

/**
 * Convert an ACF image value to a public URL.
 *
 * Supports ACF image return formats:
 * - Image array
 * - Attachment ID
 * - URL
 *
 * @param mixed $image ACF image value.
 * @return string
 */
function image_url( $image ) {
	if ( is_array( $image ) && ! empty( $image['url'] ) ) {
		return esc_url_raw( $image['url'] );
	}

	if ( is_numeric( $image ) ) {
		$url = wp_get_attachment_image_url( (int) $image, 'full' );
		return $url ? esc_url_raw( $url ) : '';
	}

	if ( is_string( $image ) ) {
		return esc_url_raw( $image );
	}

	return '';
}

/**
 * Decode the "Additional JSON-LD Properties" textarea.
 *
 * The value must be a JSON object. Reserved properties cannot replace
 * values generated by the structured fields.
 *
 * @param string $json          Raw JSON entered in ACF.
 * @param array  $reserved_keys Keys that cannot be overridden.
 * @return array
 */
function decode_additional_properties( $json, $reserved_keys = array() ) {
	if ( ! is_string( $json ) || '' === trim( $json ) ) {
		return array();
	}

	$decoded = json_decode( wp_unslash( $json ), true );

	if ( JSON_ERROR_NONE !== json_last_error() || ! is_array( $decoded ) ) {
		return array();
	}

	foreach ( $reserved_keys as $reserved_key ) {
		unset( $decoded[ $reserved_key ] );
	}

	return $decoded;
}

/**
 * Build a Schema.org PostalAddress.
 *
 * @param mixed $address ACF group field value.
 * @return array
 */
function build_address( $address ) {
	if ( ! is_array( $address ) ) {
		return array();
	}

	return clean_value(
		array(
			'@type'           => 'PostalAddress',
			'streetAddress'    => sanitize_text_field( $address['selectrum_os_street_address'] ?? '' ),
			'addressLocality'  => sanitize_text_field( $address['selectrum_os_address_locality'] ?? '' ),
			'addressRegion'    => sanitize_text_field( $address['selectrum_os_address_region'] ?? '' ),
			'postalCode'       => sanitize_text_field( $address['selectrum_os_postal_code'] ?? '' ),
			'addressCountry'   => strtoupper( sanitize_text_field( $address['selectrum_os_address_country'] ?? '' ) ),
		)
	);
}

/**
 * Normalize an array of URLs from an ACF repeater.
 *
 * @param mixed $rows ACF repeater value.
 * @return array
 */
function profile_urls( $rows ) {
	if ( ! is_array( $rows ) ) {
		return array();
	}

	$urls = array();

	foreach ( $rows as $row ) {
		$url = esc_url_raw( $row['selectrum_os_url'] ?? '' );

		if ( $url ) {
			$urls[] = $url;
		}
	}

	return array_values( array_unique( $urls ) );
}

/**
 * Build openingHoursSpecification values.
 *
 * @param mixed $rows ACF opening-hours repeater value.
 * @return array
 */
function opening_hours( $rows ) {
	if ( ! is_array( $rows ) ) {
		return array();
	}

	$hours = array();

	foreach ( $rows as $row ) {
		$days = $row['selectrum_os_day_of_week'] ?? array();

		if ( is_string( $days ) && '' !== $days ) {
			$days = array( $days );
		}

		if ( ! is_array( $days ) || empty( $days ) ) {
			continue;
		}

		$days = array_values(
			array_filter(
				array_map( 'sanitize_text_field', $days )
			)
		);

		$opens  = sanitize_text_field( $row['selectrum_os_opens'] ?? '' );
		$closes = sanitize_text_field( $row['selectrum_os_closes'] ?? '' );

		if ( empty( $days ) || ! $opens || ! $closes ) {
			continue;
		}

		$hours[] = array(
			'@type'     => 'OpeningHoursSpecification',
			'dayOfWeek' => $days,
			'opens'     => $opens,
			'closes'    => $closes,
		);
	}

	return $hours;
}

/**
 * Build areaServed values from the LocalBusiness repeater.
 *
 * @param mixed $rows ACF areas-served repeater value.
 * @return array
 */
function areas_served( $rows ) {
	if ( ! is_array( $rows ) ) {
		return array();
	}

	$areas = array();

	foreach ( $rows as $row ) {
		$area = sanitize_text_field( $row['selectrum_os_area'] ?? '' );

		if ( $area ) {
			$areas[] = $area;
		}
	}

	return array_values( array_unique( $areas ) );
}

/**
 * Build the main Organization entity.
 *
 * @param array $fields Options-page fields.
 * @return array
 */
function build_organization( $fields ) {
	if ( empty( $fields['selectrum_os_enable_schema'] ) ) {
		return array();
	}

	$schema_id = organization_id();
	$name      = sanitize_text_field( $fields['selectrum_os_name'] ?? '' );
	$url       = esc_url_raw( $fields['selectrum_os_url'] ?? '' );

	// Avoid outputting an incomplete primary entity. The @id always resolves
	// now, so only the descriptive fields are worth checking.
	if ( ! $name || ! $url ) {
		return array();
	}

	$organization = array(
		'@type'         => 'Organization',
		'@id'           => $schema_id,
		'name'          => $name,
		'legalName'     => sanitize_text_field( $fields['selectrum_os_legal_name'] ?? '' ),
		'alternateName' => sanitize_text_field( $fields['selectrum_os_alternate_name'] ?? '' ),
		'url'           => $url,
		'description'   => sanitize_textarea_field( $fields['selectrum_os_description'] ?? '' ),
		'logo'          => image_url( $fields['selectrum_os_logo'] ?? '' ),
		'foundingDate'  => sanitize_text_field( $fields['selectrum_os_founding_date'] ?? '' ),
		'telephone'     => sanitize_text_field( $fields['selectrum_os_telephone'] ?? '' ),
		'email'         => sanitize_email( $fields['selectrum_os_email'] ?? '' ),
		'address'       => build_address( $fields['selectrum_os_address'] ?? array() ),
		'sameAs'        => profile_urls( $fields['selectrum_os_same_as'] ?? array() ),
	);

	$additional = decode_additional_properties(
		$fields['selectrum_os_additional_json_ld'] ?? '',
		array( '@context', '@type', '@id' )
	);

	// Structured ACF fields take priority over additional properties.
	$organization = array_merge( $additional, $organization );

	return clean_value( $organization );
}

/**
 * Build all enabled LocalBusiness entities.
 *
 * @param array  $fields          Options-page fields.
 * @param string $organization_id Main Organization @id.
 * @param bool   $link_to_org     Whether the Organization is being emitted.
 * @return array
 */
function build_local_businesses( $fields, $organization_id, $link_to_org ) {
	if (
		empty( $fields['selectrum_os_enable_local_business_schema'] ) ||
		empty( $fields['selectrum_os_local_business_locations'] ) ||
		! is_array( $fields['selectrum_os_local_business_locations'] )
	) {
		return array();
	}

	$entities      = array();
	$allowed_types = array(
		'LocalBusiness',
		'ProfessionalService',
		'Store',
		'Restaurant',
		'MedicalBusiness',
		'FinancialService',
		'HomeAndConstructionBusiness',
		'RealEstateAgent',
	);

	foreach ( $fields['selectrum_os_local_business_locations'] as $location ) {
		if ( empty( $location['selectrum_os_enable_location'] ) ) {
			continue;
		}

		$type = sanitize_text_field( $location['selectrum_os_business_type'] ?? 'LocalBusiness' );

		if ( ! in_array( $type, $allowed_types, true ) ) {
			$type = 'LocalBusiness';
		}

		$name      = sanitize_text_field( $location['selectrum_os_name'] ?? '' );
		$schema_id = esc_url_raw( $location['selectrum_os_id'] ?? '' );
		$address   = build_address( $location['selectrum_os_address'] ?? array() );

		// Derive a stable identifier from the location name when none is given.
		if ( '' === $schema_id && '' !== $name ) {
			$schema_id = entity_id( 'localbusiness-' . sanitize_title( $name ) );
		}

		// A location needs a name and a usable address.
		if ( ! $schema_id || ! $name || empty( $address['streetAddress'] ) || empty( $address['addressLocality'] ) || empty( $address['addressCountry'] ) ) {
			continue;
		}

		$latitude  = $location['selectrum_os_latitude'] ?? '';
		$longitude = $location['selectrum_os_longitude'] ?? '';
		$geo       = array();

		if ( is_numeric( $latitude ) && is_numeric( $longitude ) ) {
			$geo = array(
				'@type'     => 'GeoCoordinates',
				'latitude'  => (float) $latitude,
				'longitude' => (float) $longitude,
			);
		}

		$entity = array(
			'@type'        => $type,
			'@id'          => $schema_id,
			'name'         => $name,
			'url'          => esc_url_raw( $location['selectrum_os_url'] ?? '' ),
			'image'        => image_url( $location['selectrum_os_image'] ?? '' ),
			'telephone'    => sanitize_text_field( $location['selectrum_os_telephone'] ?? '' ),
			'email'        => sanitize_email( $location['selectrum_os_email'] ?? '' ),
			'address'      => $address,
			'geo'          => $geo,
			'hasMap'       => esc_url_raw( $location['selectrum_os_has_map'] ?? '' ),
			'openingHoursSpecification' => opening_hours(
				$location['selectrum_os_opening_hours'] ?? array()
			),
			'priceRange'   => sanitize_text_field( $location['selectrum_os_price_range'] ?? '' ),
			'areaServed'   => areas_served(
				$location['selectrum_os_areas_served'] ?? array()
			),
		);

		if ( $link_to_org && $organization_id ) {
			$entity['branchOf'] = array(
				'@id' => $organization_id,
			);
		}

		$additional = decode_additional_properties(
			$location['selectrum_os_additional_json_ld'] ?? '',
			array( '@context', '@type', '@id', 'branchOf' )
		);

		// Structured ACF fields take priority over additional properties.
		$entity = array_merge( $additional, $entity );
		$entity = clean_value( $entity );

		if ( $entity ) {
			$entities[] = $entity;
		}
	}

	return $entities;
}

/**
 * Build the crumbs for a singular request.
 *
 * Prepends the post type archive (or the blog page for posts), then the
 * ancestor chain for hierarchical post types, then the post itself.
 *
 * @return array
 */
function breadcrumb_singular_crumbs() {
	$post = get_queried_object();

	if ( ! $post instanceof \WP_Post ) {
		return array();
	}

	$crumbs    = array();
	$post_type = get_post_type_object( $post->post_type );

	if ( $post_type && $post_type->has_archive ) {
		$crumbs[] = array(
			'name' => $post_type->labels->name ?? '',
			'url'  => get_post_type_archive_link( $post->post_type ),
		);
	} elseif ( 'post' === $post->post_type ) {
		$posts_page_id = (int) get_option( 'page_for_posts' );

		if ( $posts_page_id ) {
			$crumbs[] = array(
				'name' => get_the_title( $posts_page_id ),
				'url'  => get_permalink( $posts_page_id ),
			);
		}
	}

	// Only hierarchical post types return ancestors here.
	foreach ( array_reverse( get_post_ancestors( $post ) ) as $ancestor_id ) {
		$crumbs[] = array(
			'name' => get_the_title( $ancestor_id ),
			'url'  => get_permalink( $ancestor_id ),
		);
	}

	$crumbs[] = array(
		'name' => get_the_title( $post ),
		'url'  => get_permalink( $post ),
	);

	return $crumbs;
}

/**
 * Build the crumbs for a taxonomy term archive.
 *
 * @return array
 */
function breadcrumb_term_crumbs() {
	$term = get_queried_object();

	if ( ! $term instanceof \WP_Term ) {
		return array();
	}

	$crumbs    = array();
	$ancestors = array_reverse( get_ancestors( $term->term_id, $term->taxonomy, 'taxonomy' ) );

	foreach ( $ancestors as $ancestor_id ) {
		$ancestor = get_term( $ancestor_id, $term->taxonomy );

		if ( $ancestor instanceof \WP_Term ) {
			$crumbs[] = array(
				'name' => $ancestor->name,
				'url'  => get_term_link( $ancestor ),
			);
		}
	}

	$crumbs[] = array(
		'name' => $term->name,
		'url'  => get_term_link( $term ),
	);

	return $crumbs;
}

/**
 * Build the breadcrumb trail for the current request.
 *
 * Returns an ordered list of crumbs starting at the site home and ending on
 * the current page. Each crumb has a "name" and a "url".
 *
 * @param array $fields Options-page fields.
 * @return array
 */
function breadcrumb_trail( $fields ) {
	$home_name = sanitize_text_field( $fields['selectrum_os_name'] ?? '' );

	if ( '' === $home_name ) {
		$home_name = get_bloginfo( 'name' );
	}

	$trail = array(
		array(
			'name' => $home_name,
			'url'  => home_url( '/' ),
		),
	);

	// The blog index, when a static front page is in use.
	if ( is_home() ) {
		$posts_page_id = (int) get_option( 'page_for_posts' );

		if ( $posts_page_id ) {
			$trail[] = array(
				'name' => get_the_title( $posts_page_id ),
				'url'  => get_permalink( $posts_page_id ),
			);
		}

		return $trail;
	}

	if ( is_singular() ) {
		return array_merge( $trail, breadcrumb_singular_crumbs() );
	}

	if ( is_category() || is_tag() || is_tax() ) {
		return array_merge( $trail, breadcrumb_term_crumbs() );
	}

	if ( is_post_type_archive() ) {
		$queried_type = get_query_var( 'post_type' );

		// The query var is an array on archives that span several post types.
		if ( is_array( $queried_type ) ) {
			$queried_type = reset( $queried_type );
		}

		$post_type = $queried_type ? get_post_type_object( $queried_type ) : null;

		if ( $post_type ) {
			$trail[] = array(
				'name' => $post_type->labels->name ?? '',
				'url'  => get_post_type_archive_link( $post_type->name ),
			);
		}

		return $trail;
	}

	if ( is_author() ) {
		$author = get_queried_object();

		if ( $author instanceof \WP_User ) {
			$trail[] = array(
				'name' => $author->display_name,
				'url'  => get_author_posts_url( $author->ID ),
			);
		}

		return $trail;
	}

	if ( is_year() || is_month() || is_day() ) {
		// Read the period from the query vars rather than the first post in
		// the loop, which is not necessarily the archive being viewed.
		$year = (int) get_query_var( 'year' );

		$trail[] = array(
			'name' => (string) $year,
			'url'  => get_year_link( $year ),
		);

		if ( is_month() || is_day() ) {
			global $wp_locale;

			$month = (int) get_query_var( 'monthnum' );

			$trail[] = array(
				'name' => $wp_locale ? $wp_locale->get_month( $month ) : (string) $month,
				'url'  => get_month_link( $year, $month ),
			);

			if ( is_day() ) {
				$day = (int) get_query_var( 'day' );

				$trail[] = array(
					'name' => (string) $day,
					'url'  => get_day_link( $year, $month, $day ),
				);
			}
		}
	}

	return $trail;
}

/**
 * Build the BreadcrumbList entity for the current request.
 *
 * @param array $fields Options-page fields.
 * @return array
 */
function build_breadcrumb( $fields ) {
	if ( empty( $fields['selectrum_os_enable_breadcrumb_schema'] ) ) {
		return array();
	}

	// Breadcrumbs describe a position in the site hierarchy. The front page,
	// search results, and error pages do not have one.
	if ( is_front_page() || is_search() || is_404() ) {
		return array();
	}

	$items    = array();
	$position = 1;

	foreach ( breadcrumb_trail( $fields ) as $crumb ) {
		$name = sanitize_text_field( $crumb['name'] ?? '' );
		$url  = $crumb['url'] ?? '';

		// get_term_link() and get_permalink() can both fail.
		$url = is_string( $url ) ? esc_url_raw( $url ) : '';

		if ( '' === $name || '' === $url ) {
			continue;
		}

		$items[] = array(
			'@type'    => 'ListItem',
			'position' => $position,
			'name'     => $name,
			'item'     => $url,
		);

		$position++;
	}

	// A lone "Home" crumb carries nothing worth emitting.
	if ( count( $items ) < 2 ) {
		return array();
	}

	return array(
		'@type'           => 'BreadcrumbList',
		'@id'             => entity_id( 'breadcrumb', current_url() ),
		'itemListElement' => $items,
	);
}

/**
 * Build an ImageObject for an attachment.
 *
 * @param int    $attachment_id Attachment ID.
 * @param string $page_url      URL the image belongs to, used for the @id.
 * @return array
 */
function build_image_object( $attachment_id, $page_url ) {
	$source = wp_get_attachment_image_src( (int) $attachment_id, 'full' );

	if ( ! is_array( $source ) || empty( $source[0] ) ) {
		return array();
	}

	$caption = wp_get_attachment_caption( (int) $attachment_id );

	return clean_value(
		array(
			'@type'      => 'ImageObject',
			'@id'        => entity_id( 'primaryimage', $page_url ),
			'url'        => esc_url_raw( $source[0] ),
			'contentUrl' => esc_url_raw( $source[0] ),
			'width'      => (int) $source[1],
			'height'     => (int) $source[2],
			'caption'    => is_string( $caption ) ? sanitize_text_field( $caption ) : '',
		)
	);
}

/**
 * Build the primary image entity for the current request.
 *
 * @param string $page_url Canonical URL of the current request.
 * @return array
 */
function build_primary_image( $page_url ) {
	if ( ! is_singular() || '' === $page_url ) {
		return array();
	}

	$thumbnail_id = get_post_thumbnail_id( get_queried_object_id() );

	if ( ! $thumbnail_id ) {
		return array();
	}

	return build_image_object( $thumbnail_id, $page_url );
}

/**
 * Build the WebSite entity.
 *
 * The sitelinks searchbox that "potentialAction" used to drive was retired by
 * Google in November 2024, so no SearchAction is emitted here. The entity is
 * still worth having as the anchor for isPartOf references.
 *
 * @param array  $fields          Options-page fields.
 * @param string $organization_id Organization @id, or an empty string.
 * @return array
 */
function build_website( $fields, $organization_id ) {
	$name = sanitize_text_field( $fields['selectrum_os_name'] ?? '' );

	if ( '' === $name ) {
		$name = get_bloginfo( 'name' );
	}

	$website = array(
		'@type'       => 'WebSite',
		'@id'         => entity_id( 'website' ),
		'url'         => home_url( '/' ),
		'name'        => $name,
		'description' => get_bloginfo( 'description' ),
		'inLanguage'  => get_bloginfo( 'language' ),
	);

	if ( '' !== $organization_id ) {
		$website['publisher'] = array( '@id' => $organization_id );
	}

	return clean_value( $website );
}

/**
 * Build the WebPage entity for the current request.
 *
 * @param string $page_url         Canonical URL of the current request.
 * @param string $website_id       WebSite @id, or an empty string.
 * @param string $breadcrumb_id    BreadcrumbList @id, or an empty string.
 * @param string $primary_image_id ImageObject @id, or an empty string.
 * @return array
 */
function build_webpage( $page_url, $website_id, $breadcrumb_id, $primary_image_id ) {
	if ( '' === $page_url ) {
		return array();
	}

	$webpage = array(
		'@type'      => ( is_singular() || is_front_page() ) ? 'WebPage' : 'CollectionPage',
		'@id'        => entity_id( 'webpage', $page_url ),
		'url'        => $page_url,
		'name'       => sanitize_text_field( wp_get_document_title() ),
		'inLanguage' => get_bloginfo( 'language' ),
	);

	if ( '' !== $website_id ) {
		$webpage['isPartOf'] = array( '@id' => $website_id );
	}

	if ( '' !== $breadcrumb_id ) {
		$webpage['breadcrumb'] = array( '@id' => $breadcrumb_id );
	}

	if ( '' !== $primary_image_id ) {
		$webpage['primaryImageOfPage'] = array( '@id' => $primary_image_id );
	}

	if ( is_singular() ) {
		$post = get_queried_object();

		if ( $post instanceof \WP_Post ) {
			$webpage['datePublished'] = get_post_time( 'c', false, $post );
			$webpage['dateModified']  = get_post_modified_time( 'c', false, $post );
		}
	}

	return clean_value( $webpage );
}

/**
 * Output the JSON-LD graph in the document head.
 *
 * @return void
 */
function output_schema() {
	$fields = Settings::all();

	if ( empty( $fields ) ) {
		return;
	}

	$organization    = build_organization( $fields );
	$organization_id = organization_id();
	$locations       = build_local_businesses(
		$fields,
		$organization_id,
		! empty( $organization )
	);

	$graph = array();

	// Yoast already emits the page-level entities. Only take them over when it
	// is absent, so the two graphs never describe the same page twice.
	if ( ! Plugin::has_yoast_seo() ) {
		$page_url      = current_url();
		$breadcrumb    = build_breadcrumb( $fields );
		$primary_image = build_primary_image( $page_url );

		$website = build_website(
			$fields,
			! empty( $organization ) ? $organization_id : ''
		);

		$webpage = build_webpage(
			$page_url,
			$website['@id'] ?? '',
			$breadcrumb['@id'] ?? '',
			$primary_image['@id'] ?? ''
		);

		if ( $website ) {
			$graph[] = $website;
		}

		if ( $webpage ) {
			$graph[] = $webpage;
		}

		if ( $breadcrumb ) {
			$graph[] = $breadcrumb;
		}

		// Only ever referenced from the WebPage, so it is noise without one.
		if ( $primary_image && $webpage ) {
			$graph[] = $primary_image;
		}
	}

	if ( $organization ) {
		$graph[] = $organization;
	}

	foreach ( $locations as $location ) {
		$graph[] = $location;
	}

	if ( empty( $graph ) ) {
		return;
	}

	$json_ld = array(
		'@context' => 'https://schema.org',
		'@graph'   => $graph,
	);

	echo "\n<script type=\"application/ld+json\">\n";
	echo wp_json_encode(
		$json_ld,
		JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT
	);
	echo "\n</script>\n";
}
